### ISSUE TITLE
Examples fail to build

### ISSUE THREAD

**Issue by BitBunch** [Wollnashorn/Voronoi#2]
When trying to build the examples, they fail with the following:

```
include\xtree(1075,27): error C2440: 'static_cast': cannot convert from 'Voronoi::SparseAllocator<_Newfirst>' to 'Voronoi::SparseAllocator<_Newfirst>'
        with
        [
            _Newfirst=std::_Tree_node<Voronoi::Diagram<Vector,std::_Array_const_iterator<Vector<float>,10000>>::Bisector,void *>
        ]
        and
        [
            _Newfirst=std::_Container_proxy
        ]
```
**Environment:**
- Windows 10
- Microsoft Visual Studio 2022 Community, version 14.38.33130
- Windows 11 SDK 10.0.22621.0

**Comment by Wollnashorn** [comment]
Hi @BitBunch, thanks for the report! I assume the compilation errors only occur for debug builds, but not release builds. I will look into that and find a solution later today 🙂

**Comment by BitBunch** [comment]
Hi, thanks for the quick reply.
Yes, only for Debug builds. forgot to add that.
This looks very nice btw!

**Comment by BitBunch** [comment]
I tried your latest changes, debug now builds.
However, running the `example_simple` project, generates an exception.
Let me know if I can provide more info.

![image](https://github.com/Wollnashorn/Voronoi/assets/159258523/5f283bd3-a076-4500-9ee5-2dce403e388f)
![image](https://github.com/Wollnashorn/Voronoi/assets/159258523/60a6800c-722f-4191-8d3d-a50868fa1c28)

**Comment by Wollnashorn** [comment]
It should now be fixed, I briefly tested it with MSVC, Clang and GCC. Thanks for your feedback, I appreciate that. Hope this little implementation is useful to you

**Comment by BitBunch** [comment]
That did it for me.
Thanks for the quick responses.
